import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import providerSidebar from "./docs/provider-specification/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  provider: [{
    type: "category",
    label: "Financial Provider Specification",
    link: {
      type: "generated-index",
      title: "Financial Provider Specification API",
      description:
        "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
      slug: "/category/provider-specification",
    },
    items: providerSidebar,
  }],
};

export default sidebars;
