apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer
  labels:
    app: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer
  template:
    metadata:
      labels:
        app: developer
    spec:
      containers:
        - name: developer
          image: registry-url/developer:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 80