openapi: 3.0.0
info:
  version: 0.x
  title: aggregated
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          example: adfdfaca-48f0-4f3b-b30a-c6d97293090c
        name:
          type: string
          example: Apple Paris
      required:
      - id
      - name
  parameters: {}
paths:
  /companies:
    get:
      responses:
        '200':
          description: Retrieve a list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
  /companies/statistics:
    get:
      responses:
        '200':
          description: retreive companies list wide statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    minimum: 0
                    example: 10
                required:
                - count
  /companies/{id}:
    get:
      parameters:
      - schema:
          type: string
          minLength: 1
          example: adfdfaca-48f0-4f3b-b30a-c6d97293090c
        required: true
        name: id
        in: path
      responses:
        '200':
          description: Retrieve a company information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
    patch:
      parameters:
      - schema:
          type: string
          minLength: 1
          example: adfdfaca-48f0-4f3b-b30a-c6d97293090c
        required: true
        name: id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
              required:
              - name
      responses:
        '200':
          description: Retrieve a company information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
