openapi: 3.0.2
info:
  title: Financial Provider specification.
  description: |-
    This describe the specification that a financial provider must follow, to provide it's client (wealth management companies) an integrated experience of their data into a wealth aggregator (_Wealthcome_)

    Some useful links:
    - [Wealthcome](https://wealthcome.fr)
  termsOfService: https://www.wealthcome.fr/conditions-generales-utilisation
  contact:
    email: dev@wealthcome.fr
  version: 0.1.0
externalDocs:
  description: Find out more about the specification
  url: https://developer.wealthcome.fr
servers:
  - url: /v0
tags:
  - name: company
    description: Everything about the company entity.
    x-displayName: Company
    # externalDocs:
    #   description: Find out more
    #   url: http://swagger.io
  - name: manager
    description: Manager related operations.
    x-displayName: Manager
paths:
  # Company
  /companies:
    get:
      tags:
        - company
      summary: List all companies.
      description: This call is not paginated, and will return all companies.
      operationId: listCompanies
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/company"
  /companies/{company_id}:
    get:
      tags:
        - company
      summary: Get a company detailed informations.
      operationId: company_by_id
      parameters:
        - name: company_id
          in: path
          required: true
          description: The ID of the company to retrieve.
          schema:
            type: string
            minLength: 1
      responses:
        "200":
          description: A company object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/company"
        "404":
          description: Company not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Company not found"

  # Manager
  /managers:
    get:
      tags:
        - manager
      summary: List all managers.
      description: This call is not paginated, and will return all managers.
      operationId: listManagers
      responses:
        "200": # status code
          description: A array of managers entities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/manager"
components:
  schemas:
    company:
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
      required:
        - id
        - name
    manager:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          minLength: 1
        email:
          type: string
          format: email
        phone:
          type: string
          format: phone
        companies:
          type: array
          items:
            type: string
      required:
        - id
        - name
        - companies
