name: Publish

## Build and push the docker image into the registry

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      registry_url:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      # Build and push
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.registry_url }}/${{ inputs.image }}:${{ inputs.tag }}
