name: validate

on:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4

      - name: Run Biome
        run: npx biome ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GIT_PAT_PULL }}
      
      - name: Configure Git for private repos
        run: git config --global url."https://${{ secrets.GIT_PAT_PULL }}@github.com/".insteadOf "https://github.com/"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
